directory:
- ../envs/local
download-external-modules: false
evaluate-variables: true
external-modules-download-path: .external_modules
framework:
- terraform
secrets-scan-file-type: []
skip-check:
- LOW
