apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
    service: app
spec:
  type: ClusterIP
  selector:
    app: app
  ports:
  - name: tcp-app
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: kecmiriz.azurecr.io/app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
          # Logging
            - name: Logging__LogLevel__Default
              value: Warning
      hostname: app
      restartPolicy: Always
