name: 'dev-deploy'

on:
  workflow_dispatch:

jobs:
  terraform-test:
    uses: ./.github/workflows/template-deploy.yaml
    with:
      var_name: ''
      environment: ''
      working_directory: ''
    secrets: inherit
