run:
  skip-dirs:
    - env
  skip-files:
    - "*.sh"
    - "*.bat"

linters:
  disable-all: true
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
